spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 8c52e96f8bbd07c941c376c721e9f8cc
            client-secret: iIwv22CMj8YYIGsjgaoVRj82HWEmm2AO
            redirect-uri: http://localhost/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
          naver:
            client-id : cfzdBqeXodwiA7Ow_KxP
            client_secret : Qgln4dA2rD
            redirect-uri: http://localhost/login/oauth2/code/naver
            authorization-grant-type : authorization_code
            scope :
              - name
              - email
              - nickname
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri : https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response