server:
  port: 8080


spring:
  datasource:
    url : jdbc:mysql://127.0.0.1:3306/miristockdb?characterEncoding=UTF-8&serverTimezone=UTC
    username: ssafy
    password: ssafy
    driver-class-name : com.mysql.cj.jdbc.Driver
  jpa:
    database : mysql
    database-platform : org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
    properties:
      hibernate:
        format_sql : true
        show_sql : true
        use_sql_comments: true
  redis:
    host: 127.0.0.1
    port: 6379
    passwor: 'ssafy'
  profiles:
    include: oauth
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**,public/**
    # Live Reload
logging:
  level:
    org:
      hibernate: info
      type: trace



