server:
  port: 80


spirng:
  datasource:
    url : jdbc:mysql://localhost:3306/miristockdb?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: ssafy
    password: ssafy
    driver-class-name : com.mysql.cj.jdbc.Driver
  jpa:
    database : mysql
    database-platform : org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
    properties:
      hibernate:
        format_sql : true
        show_sql : true
        use_sql_comments: true

logging:
  level:
    org:
      hibernate: info